# https://theweeklychallenge.org/blog/perl-weekly-challenge-361/

# TASK 1
# https://arraybox.dev/#39mi

Zeckendorf ← ▽⊙◌⤚(⍥(⊂↘₁⟜(⊃(⌊÷)◿⊢))⊸⧻)⍢(⊂/+⊸↙₂|>⊢) 1_1

⊟⟜≡(□Zeckendorf) 4_12_20_96_100

# TASK 2
# https://arraybox.dev/#12MA

Data₁ ← [0_0_0_0_1_0
         0_0_0_0_1_0
         0_0_0_0_1_0
         0_0_0_0_1_0
         0_0_0_0_0_0
         0_0_0_0_1_0]

Data₂ ← [0_1_0_0 0_0_1_0 0_0_0_1 1_0_0_0]

Party ← ⨬¯1⊣⊸⧻⊚/↧↥˙⊞=⇡⊸⧻

∩Party Data₁ Data₂
